services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.4
    container_name: elasticsearch
    environment: [
      'ES_JAVA_OPTS=-Xms2g -Xmx2g',
      'bootstrap.memory_lock=true',
      'discovery.type=single-node',
      'xpack.security.enabled=false',
      'xpack.security.enrollment.enabled=false' ]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./
    container_name: movies_app
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_ELASTIC_SEARCH_HOST=elasticsearch
    ports:
      - "8080:8080"
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge